#!/bin/sh
# System startup script for Dual cameras

### BEGIN INIT INFO
# Provides:          dual_cameras
# Required-Start:    $local_fs S56moonraker
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dual cameras daemon
# Description:       Starts the Dual cameras daemon.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DESC="dual cameras daemon"
NAME="dual cameras"
PIDFILE=/var/run/dual_cameras.pid

case "$1" in
start)  echo "Starting Dual cameras"
        start-stop-daemon --start --quiet --exec /usr/data/startup_dual_cameras.sh \
                          --background --pidfile $PIDFILE --make-pidfile \
                          --chuid root --user root
        ;;
stop)   echo "Not implemented"
        ;;
restart) log_daemon_msg "Restarting" $NAME
        $0 stop
        $0 start
        ;;
reload|force-reload)
        echo "Reloading configuration not supported"
        ;;
*)      echo "Usage: /etc/init.d/dual_cameras {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
